
title: jsaf
email: jafpedersen@gmail.com
description: jsaf's personal website
baseurl: ""
domain: jsaf.dk
url: "https://jsaf.dk"
github_username:  jsaf0

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light"
  back_home_text: "← back"
  date_format: "%Y-%m-%d"
  show_description: true
  lowercase_titles: false

plugins:
  - jekyll-feed
